import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { LayoutProvider } from "../components/layoutProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kalabari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          {children}  
        </LayoutProvider>
      </body>
    </html>
  );
}
